name: built_redux_dev_tools
version: 0.0.2
description:
   built_redux dev tools store
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/built_redux_dev_tools
dependencies:
  built_redux: '>=6.0.0 <8.0.0'
  built_collection: '>=1.0.0 <4.0.0'
  built_value: '>=4.0.0 <6.0.0'

dev_dependencies:
  build_runner: ^0.6.0
  built_value_generator: '>=4.0.0 <6.0.0'
  source_gen: ^0.7.0

environment:
  sdk: '>=1.17.1 <2.0.0'
